### ISSUE TITLE
Unknown devices

### ISSUE THREAD

**Issue by carlo-dev-git** [STMicroelectronics/cmsis-device-g4#2]
the following devices are not documented neither on the STM website nor in the CubeMX software
* STM32G471xx
* STM32GBK1CB

**Comment by ALABSTM** [comment]
Hi @carlo-dev-git,

Your question has been forwarded to our development teams. We will get back to you as soon as we get their answer.

With regards,

**Comment by ALABSTM** [comment]
Hi @carlo-dev-git,

I hope you are fine. Back to you about your question. Both `STM32G471xx` and `STM32GBK1CB` have been released on the market then discontinued short after as replaced by other STM32G4xx devices covering the same features and characteristics. This explains why you could not find any documentation.

On the other hand, as they may still be used by customers in the frame of a number of projects, we continue keeping any aspects related to these two devices in our firmware.

I hope this answers your question. Please allow me to close this issue.

With regards,
